before_install:
  - sudo add-apt-repository -y ppa:ubuntu-elisp/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq python3
  - sudo apt-get install -qq python3-pip
notifications:
  email:
    on_success: never
    on_failure: never